name: Node.js test and Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: ['18']
        java: ['8']
        vite-version: ['4', '5', '6']
        include:
          - os: ubuntu-latest
            node-version: '20'
            java: '8'
            vite-version: '7'

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Set up JDK ${{ matrix.java }}
      uses: coursier/setup-action@v1
      with:
        jvm: temurin:1.${{ matrix.java }}
        apps: sbt

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies with Vite ${{ matrix.vite-version }}
      run: npm install -D @types/node@${{ matrix.node-version }} && npm install vite@${{ matrix.vite-version }}
    - name: Run sbt once in the test project to make sure sbt is downloaded
      run: sbt projects
      working-directory: ./test/testproject
    - name: Perform unit test
      run: npm test
    - name: Build
      run: npm run build
